# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true

[profile.baobab]
eth_rpc_url = 'https://archive-en.baobab.klaytn.net'

[profile.cypress]
eth_rpc_url = 'https://archive-en.cypress.klaytn.net'

[profile.homi]
eth_rpc_url = 'http://127.0.0.1:8551'

[rpc_endpoints]
cypress = 'https://archive-en.cypress.klaytn.net'
baobab = 'https://archive-en.baobab.klaytn.net'
local = 'http://127.0.0.1:8545'
homi = 'http://127.0.0.1:8551'
