#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

files=$(git diff --cached --name-only --diff-filter=ACM -- *.sol)
if [ ! -z "$files" ]; then
    forge fmt
    forge test --silent
fi

files=$(git diff --cached --name-only --diff-filter=ACM -- *.ts *.md)
if [ ! -z "$files" ]; then
    npx lint-staged
fi
